### ISSUE TITLE
Getting error - None values not supported when running ram.py

### ISSUE THREAD

**Issue by tusharkgerg** [songyouwei/SA-DL#2]
Here is the traceback:

Build model...
Traceback (most recent call last):
  File "ram.py", line 117, in <module>
    model = RecurrentAttentionMemory()
  File "ram.py", line 86, in __init__
    x = shared_attention((memory, x))
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/base_layer.py", line 239, in __call__
    output = super(Layer, self).__call__(inputs, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 714, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/Users/tushar/workspace/python/impact/songyouwei/SA-DL/attention_layer.py", line 66, in call
    score *= K.cast(mask, K.floatx())
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/backend.py", line 1226, in cast
    return math_ops.cast(x, dtype)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 779, in cast
    x = ops.convert_to_tensor(x, name="x")
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 950, in convert_to_tensor
    as_ref=False)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1040, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1026, in _autopacking_conversion_function
    return _autopacking_helper(v, inferred_dtype, name or "packed")
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 988, in _autopacking_helper
    constant_op.constant(elem, dtype=dtype, name=str(i)))
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 214, in constant
    value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 421, in make_tensor_proto
    raise ValueError("None values not supported.")
ValueError: None values not supported.

Is there something that needs fixing?

**Comment by studiawan** [comment]
Hi @tusharkgerg, did you find any solution for this issue? I have the same issue.
